name: Cloud Native Sovereign Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'sitios-web/**'
      - 'firebase.json'
      - '.github/workflows/deploy.yml'

permissions:
  contents: read
  id-token: write

jobs:
  deploy-sovereign-cloud:
    name: Deploy to Google Cloud (Firebase)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud (OIDC)
        id: 'auth'
        uses: google-github-actions/auth@v2
        with:
          project_id: cs-poc-aguy0wkzgf55jarewtxljk9
          workload_identity_provider: projects/831861990394/locations/global/workloadIdentityPools/ahi-pool/providers/ahi-provider
          service_account: github-actions-sa@cs-poc-aguy0wkzgf55jarewtxljk9.iam.gserviceaccount.com
          create_credentials_file: true

      - name: 'Instalar Firebase y Desplegar (Soberano)'
        run: |
          npm install -g firebase-tools
          firebase deploy --only hosting --project cs-poc-aguy0wkzgf55jarewtxljk9
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}
